### ISSUE TITLE
Download specific large files

### ISSUE THREAD

**Issue by yewero** [caleblareau/mtscATACpaper_reproducibility#1]
The file `mtscATACpaper_large_data_files` is too large.
Is it possible to download specific files in `mtscATACpaper_large_data_files`?
For example, the files in the following codes:
```
SE1 <- getCountsFromFrags_GM11906("../../../mtscATACpaper_large_data_files/source/cellranger_output/Mix_Fix_1hr_fragments.tsv.gz", "../output/data1_meta.tsv")
SE6 <- getCountsFromFrags_GM11906("../../../mtscATACpaper_large_data_files/source/cellranger_output/Mix_Fix_6hr_fragments.tsv.gz", "../output/data6_meta.tsv")
```

**Comment by caleblareau** [comment]
I can look into a different way of hosting the files, but for now, the fragments files that you indicated should be hosted on the GEO accession.

On Aug 17, 2020, at 1:49 AM, Feng Tian <notifications@github.com<mailto:notifications@github.com>> wrote:



The file mtscATACpaper_large_data_files is too large.
Is it possible to download specific files in mtscATACpaper_large_data_files?
For example, the files in the following codes:

SE1 <- getCountsFromFrags_GM11906("../../../mtscATACpaper_large_data_files/source/cellranger_output/Mix_Fix_1hr_fragments.tsv.gz", "../output/data1_meta.tsv")
SE6 <- getCountsFromFrags_GM11906("../../../mtscATACpaper_large_data_files/source/cellranger_output/Mix_Fix_6hr_fragments.tsv.gz", "../output/data6_meta.tsv")

**Comment by yewero** [comment]
Sorry, but there are no files called `Mix_Fix_1hr_fragments.tsv.gz` or `Mix_Fix_6hr_fragments.tsv.gz` on GEO ([GSE142745](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE142745)).

**Comment by caleblareau** [comment]
Apologies-- based on how the renaming happened, this is less clear

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE142740
```
GSM4238432_mtscATACseq1.fragments.tsv.gz = Mix_Fix_1hr_fragments.tsv.gz
GSM4238433_mtscATACseq2.fragments.tsv.gz = Mix_Fix_1hr_fragments.tsv.gz
```

**Comment by yewero** [comment]
Thanks. There is a typo in your reply. It should be:
```
GSM4238432_mtscATACseq1.fragments.tsv.gz = Mix_Fix_1hr_fragments.tsv.gz
GSM4238433_mtscATACseq2.fragments.tsv.gz = Mix_Fix_6hr_fragments.tsv.gz
```

**Comment by caleblareau** [comment]
Hi @yewero, I've moved the large data files to OSF that should enable selectively downloading specific files: https://osf.io/bupge/

I hope that this helps.
-Caleb

**Comment by yewero** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi Caleb,
        Thanks very much!
    
        
            
        
    Best
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    


----------------------------Feng TianBIOPIC, ICG, CBI and CLSPeking University, China, 100871




        
    
     

    On 8/30/2020 02:35，Caleb Lareau<notifications@github.com> wrote： 



Hi @yewero, I've moved the large data files to OSF that should enable selectively downloading specific files: https://osf.io/bupge/
I hope that this helps.
-Caleb

**Comment by yewero** [comment]
@caleblareau Thanks very much!
