### ISSUE TITLE
generating input data

### ISSUE THREAD

**Issue by rtyags** [caleblareau/mtscATACpaper_reproducibility#3]
Hi

I am trying to replicate the generation of the input data for this work, which is given in the cellranger_output directory. Presumably this data is the output of "cellranger-atac count" command with the fastq files from SRA and hg19 reference genome. Is that correct? However, I don't see the files expected from a count output there. Could you explain what these files represent and how to generate them?

Thanks

**Comment by caleblareau** [comment]
Yes it should be cellranger-atac count for our modified hg19 reference (https://github.com/caleblareau/mgatk/wiki/Increasing-coverage-from-10x-processing) Is there a specific set of files that doesn't make sense?

**Comment by rtyags** [comment]
Thanks for the response Caleb. I was able to figure these out.
