### ISSUE TITLE
Fig 6h reproducibility

### ISSUE THREAD

**Issue by BiotechPedro** [caleblareau/mtscATACpaper_reproducibility#5]
Hi Caleb!

First of all, thank you for this AMAZING resource, both the mgatk software and the reproducible scripts. It's super clearly explained! 

I've been trying to reproduce all the plots from figure 6, based on the scripts in folder `mtscATACpaper_reproducibility/figure_paired_cd34_pbmc` but could find the code for obtaining the figure 6h (cumulative proportion of cells per clone). Could you share it please?

Thanks A LOT!

Pedro

**Comment by caleblareau** [comment]
oh weird; that script must not have been committed... I've since switched computers so I'm not sure that I have the exactly thing, but the ggplot function for doing these plots would be

`ggplot(...) + stat_ecdf() + scale_x_log10()`

**Comment by BiotechPedro** [comment]
Yep, thank you again! AWESOME job :)

**Comment by caleblareau** [comment]
thanks so much :) glad the resource is helpful!
